export const API_ROUTES = {
  CUSTOM_LOGIN: '/api/custom/login',
  CUSTOM_AUTOMATION_DASHBOARD: (id) => `/api/custom/automations/${id}/dashboard`,
  CUSTOM_AUTOMATION_ACTIVITY: (id) => `/api/custom/automations/${id}/activity`,
  CUSTOM_AUTOMATION_ERRORS: (id) => `/api/custom/automations/${id}/errors`,
  CUSTOM_AUTOMATION_ACCOUNTS: (id) => `/api/custom/automations/${id}/accounts`,
  CUSTOM_AUTOMATION_ACCOUNTS_BAN_STATS: (id) => `/api/custom/automations/${id}/accounts/ban-stats`,
  CUSTOM_AUTOMATION_ACCOUNTS_HEALTH_CHECK: (id) => `/api/custom/automations/${id}/accounts/health-check`,
  CUSTOM_AUTOMATION_ACCOUNT_SPAMBLOCK_CHECK: (id, accountId) =>
    `/api/custom/automations/${id}/accounts/${accountId}/spamblock-check`,
  CUSTOM_AUTOMATION_ACCOUNTS_SETUP_TEMPLATES: (id) => `/api/custom/automations/${id}/accounts/setup-templates`,
  CUSTOM_AUTOMATION_ACCOUNTS_PREPARE: (id) => `/api/custom/automations/${id}/accounts/prepare`,
  CUSTOM_AUTOMATION_ACCOUNTS_PREPARE_STATUS: (id) => `/api/custom/automations/${id}/accounts/prepare-status`,
  CUSTOM_AUTOMATION_ACCOUNTS_WARMUP_START: (id) => `/api/custom/automations/${id}/accounts/warmup/start`,
  CUSTOM_AUTOMATION_ACCOUNTS_QR_START: (id) => `/api/custom/automations/${id}/accounts/qr/start`,
  CUSTOM_AUTOMATION_ACCOUNTS_QR_STATUS: (id) => `/api/custom/automations/${id}/accounts/qr/status`,
  CUSTOM_AUTOMATION_ACCOUNTS_QR_2FA: (id) => `/api/custom/automations/${id}/accounts/qr/verify_2fa`,
  CUSTOM_AUTOMATION_ACCOUNTS_SMS_REQUEST: (id) => `/api/custom/automations/${id}/accounts/sms/request`,
  CUSTOM_AUTOMATION_ACCOUNTS_SMS_VERIFY: (id) => `/api/custom/automations/${id}/accounts/sms/verify`,
  CUSTOM_AUTOMATION_SETTINGS: (id) => `/api/custom/automations/${id}/settings`,
  CUSTOM_AUTOMATION_CHATS: (id) => `/api/custom/automations/${id}/chats`,
  CUSTOM_AUTOMATION_CHAT: (id, chatId) => `/api/custom/automations/${id}/chats/${chatId}`,
  CUSTOM_AUTOMATION_CHAT_MESSAGES: (id, chatId) => `/api/custom/automations/${id}/chats/${chatId}/messages`,
  CUSTOM_AUTOMATION_CHAT_IMPORT: (id) => `/api/custom/automations/${id}/chats/bulk-import`,
  CUSTOM_AUTOMATION_CHAT_IMPORT_JOBS: (id) => `/api/custom/automations/${id}/chats/import-jobs`,
  CUSTOM_AUTOMATION_CHAT_INSPECT_COMMENTS: (id) => `/api/custom/automations/${id}/chats/inspect-comments`,
  CUSTOM_AUTOMATION_CHAT_INSPECT_STATUS: (id) => `/api/custom/automations/${id}/chats/inspect-status`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY: (id) => `/api/custom/automations/${id}/chats/discovery`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY_APPROVE: (id, taskId) =>
    `/api/custom/automations/${id}/chats/discovery/${taskId}/approve`,
  CUSTOM_AUTOMATION_CHAT_DISCOVERY_REJECT: (id, taskId) =>
    `/api/custom/automations/${id}/chats/discovery/${taskId}/reject`,
  CUSTOM_AUTOMATION_CHAT_JOIN: (id) => `/api/custom/automations/${id}/chats/join`,
  CUSTOM_AUTOMATION_CHAT_MONITOR: (id) => `/api/custom/automations/${id}/chats/monitor`,
  CUSTOM_AUTOMATION_LEADS: (id) => `/api/custom/automations/${id}/leads`,
  CUSTOM_AUTOMATION_LEAD: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}`,
  CUSTOM_AUTOMATION_LEAD_MESSAGES: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}/messages`,
  CUSTOM_AUTOMATION_LEAD_STATUS: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}/status`,
  CUSTOM_AUTOMATION_LEAD_TRANSFER: (id, leadId) => `/api/custom/automations/${id}/leads/${leadId}/transfer`,
  CUSTOM_AUTOMATION_DMP_IMPORTS: (id) => `/api/custom/automations/${id}/dmp/imports`,
  CUSTOM_AUTOMATION_DMP_ORDERS: (id) => `/api/custom/automations/${id}/dmp/orders`,
  CUSTOM_AUTOMATION_DMP_POLL: (id) => `/api/custom/automations/${id}/dmp/poll`,
  CUSTOM_AUTOMATION_AMOCRM_CONNECTION: (id) => `/api/custom/automations/${id}/amocrm/connection`,
  CUSTOM_AUTOMATION_AMOCRM_CREDENTIALS: (id) => `/api/custom/automations/${id}/amocrm/credentials`,
  CUSTOM_AUTOMATION_AMOCRM_OAUTH_START: (id) => `/api/custom/automations/${id}/amocrm/oauth/start`,
  CUSTOM_AUTOMATION_AMOCRM_SYNC: (id) => `/api/custom/automations/${id}/amocrm/sync`,
  CUSTOM_AUTOMATION_DMP_WEBHOOK_ROTATE: (id) => `/api/custom/automations/${id}/dmp/webhook-secret/rotate`,
  CUSTOM_AUTOMATION_TELEGRAM_BOT: (id) => `/api/custom/automations/${id}/telegram-bot`,
  CUSTOM_AUTOMATION_GOOGLE_SHEETS: (id) => `/api/custom/automations/${id}/google-sheets`,
  CUSTOM_AUTOMATION_PROMPTS: (id) => `/api/custom/automations/${id}/prompts`,
  CUSTOM_AUTOMATION_PROMPT: (id, promptId) => `/api/custom/automations/${id}/prompts/${promptId}`,
  CUSTOM_AUTOMATION_PROMPT_TOGGLE: (id, promptId) => `/api/custom/automations/${id}/prompts/${promptId}/toggle`,
  CUSTOM_AUTOMATION_PROMPT_TEST: (id, promptId) => `/api/custom/automations/${id}/prompts/${promptId}/test`,
  CUSTOM_AUTOMATION_CHAT_NEUROCOMMENTING_CONFIG: (id, chatId) =>
    `/api/custom/automations/${id}/chats/${chatId}/neurocommenting-config`,
  CUSTOM_AUTOMATION_CHAT_NEUROCOMMENTING_RUN: (id) => `/api/custom/automations/${id}/chats/neurocommenting`,
  CUSTOM_AUTOMATION_CHAT_DISCUSSION_CONFIG: (id, chatId) =>
    `/api/custom/automations/${id}/chats/${chatId}/discussion-config`,
  CUSTOM_AUTOMATION_CHAT_DISCUSSION_RUN: (id) => `/api/custom/automations/${id}/chats/discussion`,
  CUSTOM_AUTOMATION_CHAT_SHILLING_CONFIG: (id, chatId) =>
    `/api/custom/automations/${id}/chats/${chatId}/shilling-config`,
  CUSTOM_AUTOMATION_CHAT_SHILLING_RUN: (id) => `/api/custom/automations/${id}/chats/shilling`,
};

export const NAVIGATION_ROUTES = {
  CUSTOM_LOGIN: '/login',
  CUSTOM_AUTOMATION_DASHBOARD: () => '/dashboard',
  CUSTOM_AUTOMATION_ACTIVITY: () => '/activity',
  CUSTOM_AUTOMATION_ERRORS: () => '/errors',
  CUSTOM_AUTOMATION_ACCOUNTS: () => '/accounts',
  CUSTOM_AUTOMATION_SETTINGS: () => '/settings',
  CUSTOM_AUTOMATION_CHATS: () => '/chats',
  CUSTOM_AUTOMATION_CHAT_DISCOVERY: () => '/chats/discovery',
  CUSTOM_AUTOMATION_LEADS: () => '/leads',
  CUSTOM_AUTOMATION_LEAD_CHAT: (_id, leadId) => `/leads/${leadId}/chat`,
  CUSTOM_AUTOMATION_DMP: () => '/dmp',
  CUSTOM_AUTOMATION_AMOCRM: () => '/amocrm',
  CUSTOM_AUTOMATION_PROMPTS: () => '/prompts',
  CUSTOM_AUTOMATION_PROMPT_EDIT: (_id, promptId) => `/prompts/${promptId}/edit`,
};
